language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql         

sudo: false

cache:
    - $HOME/.composer/cache/files

before_install:
    - mysql -u root -e 'CREATE DATABASE todolistproject_test;'
    - mysql -u root -e 'CREATE DATABASE todolistproject;'
    - mysql -e 'USE todolistproject_test; create table user'

before_script:
    - composer install  

script:
    - vendor/bin/phpunit