language: php
php:
  - '7.4.9'
services:
  - mysql 

before_script:
  - curl -s http://getcomposer.org/installer | php
  - composer install -n

script:
   - vendor/bin/phpunit --coverage-clover build/coverage/xml
   - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

