language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql         

sudo: false

cache:
    - $HOME/.composer/cache/files

before_install:
    - mysql -u root -e 'CREATE DATABASE todolistproject_test;'
    - mysql -u root -e 'CREATE DATABASE todolistproject;'
    - mysql -e 'USE todolistproject_test; create table user(
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,
  `roles` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:array)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_8D93D649F85E0677` (`username`),
  UNIQUE KEY `UNIQ_8D93D649E7927C74` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=27 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;'

before_script:
    - composer install  

script:
    - vendor/bin/phpunit