language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql   

test:
  adapter: mysql2
  database: todolisproject
  username: travis
  encoding: utf8      

sudo: false

cache:
    - $HOME/.composer/cache/files

before_install:
    - mysql -u root -e 'CREATE DATABASE todolistproject;'

before_script:
    - composer install  

script:
    - vendor/bin/phpunit
