language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql   

test:
  adapter: mysql2
  database: todolisproject_test
  username: travis
  encoding: utf8      

sudo: false

cache:
    - $HOME/.composer/cache/files

# before_install:
#     - mysql -u root -e 'CREATE DATABASE todolistproject; USE todolistproject; CREATE TABLE user (id int NOT NULL AUTO_INCREMENT,username varchar(25) NOT NULL,password varchar(64) NOT NULL,email varchar(60) NOT NULL,roles longtext NOT NULL,PRIMARY KEY (id),UNIQUE KEY UNIQ_8D93D649F85E0677 (username),UNIQUE KEY UNIQ_8D93D649E7927C74 (email));'
#     - mysql -u root -e 'CREATE DATABASE todolistproject_test; USE todolistproject_test; CREATE TABLE user (id int NOT NULL AUTO_INCREMENT,username varchar(25) NOT NULL,password varchar(64) NOT NULL,email varchar(60) NOT NULL,roles longtext NOT NULL,PRIMARY KEY (id),UNIQUE KEY UNIQ_8D93D649F85E0677 (username),UNIQUE KEY UNIQ_8D93D649E7927C74 (email));'
    # - composer require symfony/runtime
    # - php ./bin/console doctrine:migrations:diff
    # - php ./bin/console doctrine:migrations:migrate --no-interaction
    # - KERNEL_CLASS='App\Kernel'
    # - APP_SECRET='$ecretf0rt3st'
    # - SYMFONY_DEPRECATIONS_HELPER=999999
    # - PANTHER_APP_ENV=panther
    # - PANTHER_ERROR_SCREENSHOT_DIR=./var/error-screenshots    
    # - php bin/console doctrine:fixtures:load -n --env=test

# before_script:
#     - composer install  

# script:
#     - vendor/bin/phpunit

install:
    - composer install --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
script:
    - ./vendor/bin/simple-phpunit --coverage-text --colors
