language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql   

test:
  adapter: mysql2
  database: todolisproject_test
  username: travis
  encoding: utf8      

sudo: false

cache:
    - $HOME/.composer/cache/files

install:
    - composer install --prefer-dist --no-interaction
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
script:
    - ./vendor/bin/simple-phpunit --coverage-text --colors
