language: php

matrix:
    include:
        - php: 7.4

services:
  - mysql   

test:
  adapter: mysql2
  database: symfony
  username: travis
  encoding: utf8      

sudo: false

cache:
    - $HOME/.composer/cache/files

before_install:
    # - mysql -u root -e 'CREATE DATABASE todolistproject_test;'
    - mysql -u root -e 'CREATE DATABASE todolistproject;'
    # - mysql -e 'USE todolistproject_test; create table user(`id` int NOT NULL AUTO_INCREMENT,`username` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL,`password` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,`email` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,`roles` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '(DC2Type:array)',PRIMARY KEY (`id`),UNIQUE KEY `UNIQ_8D93D649F85E0677` (`username`),UNIQUE KEY `UNIQ_8D93D649E7927C74` (`email`)) 
    #   - php bin/console doctrine:database:create --env=test
    #   - php bin/console doctrine:schema:create --env=test
    #   - php bin/console doctrine:fixtures:load -n --env=test

before_script:
    - composer install  
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n

script:
    # - vendor/bin/phpunit
    - vendor/bin/simple-phpunit --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/codacycoverage clover build/logs/clover.xml